### ISSUE TITLE
html - bootstrap

### ISSUE THREAD

**Issue by neox387** [wilbertom/flask-reverse-proxy#5]
Working good except I have no idea how to get the html code right, for example pressing a button on the navbar it keeps going to /settings & not the custom '/prem/settings' same for pressing buttons  on login

[https://github.com/neox387/premiumizer/blob/master/templates/base.html#L34-L54](https://github.com/neox387/premiumizer/blob/master/templates/base.html#L34-L54)

any idea for fixing the hrefs ? using nginx

EDIT: tought this  would fix it but doesn't seem to do anything :(
`sub_filter` '<a href="/' '<a href="/prem/';`

**Comment by neox387** [comment]
nvm fixt it all url_for()

**Comment by wilbertom** [comment]
Glad you figured this out!
